### ISSUE TITLE
Add a way to suppress logging

### ISSUE THREAD

**Issue by Jovaage** [OpenZWave/node-openzwave-shared#156]
You can give the option parameter `ConsoleOutput: false`, but this does‘t suppress all logging.

This is logged every time the package is used and initialized.
```
initialising OpenZWave addon (/home/vaage/z-wave-test/node_modules/openzwave-shared/lib/../build/Release/openzwave_shared.node)
Initialising OpenZWave 1.4.164 binary addon for Node.JS.
        OpenZWave Security API is ENABLED
        ZWave device db    : /usr/local/etc/openzwave
        User settings path : /home/vaage/z-wave-test/node_modules/openzwave-shared/build/Release/../../
        Option Overrides : --ConsoleOutput false
```

There should be a way to suppress these loggings as well.

**Comment by ekarak** [comment]
So, please submit a fix for it. I think that we should have at least some basic feedback the addon has loaded up properly and is pointing to the correct directories (as you might have installed OpenZWave in multiple locations)

**Comment by DvStephen** [comment]
Would you still be open to a PR to fix this?, trying to use this library in an application setup is frustrating because the library assumes it's OK for it to use stdout, but stdout should be owned by the application layer, not a library, for example- if an application was to push zwave messages to stdout, there is no nice way to use this library as it *always* wants to push its own messages about the addon loading first.

Whilst it is useful for these messages during development, we already specify `ConsoleOutput` and `Logging` as false yet still receive these stdout messages..

**Comment by ekarak** [comment]
of course, please raise a PR.

On 14 Mar 2018 4:47 pm, "DvStephen" <notifications@github.com> wrote:

Would you still be open to a PR to fix this?, trying to use this library in
an application setup is frustrating because the library assumes it's OK for
it to use stdout, but stdout should be owned by the application layer, not
a library, for example- if an application was to push zwave messages to
stdout, there is no nice way to use this library as it *always* wants to
push its own messages about the addon loading first.

Whilst it is useful for these messages during development, we already
specify ConsoleOutput and Logging as false yet still receive these stdout
messages..

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/OpenZWave/node-openzwave-shared/issues/156#issuecomment-373047424>,
or mute the thread
