### ISSUE TITLE
State of Door/Window not detected

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#191]
We have a Door/Window from Aeotec.
In MinOZW (openzwave sniffer), when we open and close the magnet, we see the state change (Basic Set).
But we do not see any activity in node-openzwave-shared, that's no events is emitted.

**Comment by ekarak** [comment]
NodeEvents that originate from the device (such as manual control buttons and door/window sensors) typically involve that the controller has set up an association group with the device so that it will receive a message when the device changes state.
- What do the OpenZWave logs say about the association groups for this node?
- How do these logs differ from the logs that MinOZW emits? does it implicitly enable polling perhaps?

*again and again* I must state: the `node-openzwave-shared` is not enabling/disabling any features of OpenZWave, other than what other C/C++ apps (like MinOZW). It simply exposes the API to Javascript.
