### ISSUE TITLE
SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE

### ISSUE THREAD

**Issue by ChristianGr1974** [OpenZWave/node-openzwave-shared#220]
Hi,

I'am trying to issue a StopLevelChange command to a roller shutter device (FGRM222). How can I achieve this? There is a "bool SwitchMultilevel::StopLevelChange" method in the openzwave library, but how can I trigger this method? Or is there an other way to stop the shutter from moving.

best regards,
Christian

**Comment by AlCalzone** [comment]
If you're starting the level change by "pressing" the virtual open/close button on your device (i.e. setting the button value to true), you can stop the level change by "releasing" it, i.e. setting the button value to false.

Maybe that also works when the StartLevelChange was not due to a button press.

**Comment by ekarak** [comment]
Agree with AlCalzone, the `SwitchMultilevel::StopLevelChange` is not part of the `Manager` API and should not be directly exposed to Javascript.
I'm resolving this issue, please reopen if the suggested method (calling `PressButton/ReleaseButton`) doesn't work as expected, then we can try a workaround.
