### ISSUE TITLE
ZW100 Aeotec

### ISSUE THREAD

**Issue by ptorrent** [OpenZWave/node-openzwave-shared#261]
Hello,

Sometimes the temperature goes up to 70 °C. It seems that the temperature changes of unit (Celsius to Fahrenheit or other bug ? ) without any reason. The unit parameter is correctly set to Celsius.

I've 10 TW100 connected to my network. All of theme have the same strange value (sometimes).

Does anyone have the same problem?

Is this problem linked to the module or the device directly?

Thanks for your help !

**Comment by ptorrent** [comment]
After some investiagation, it's seems that value is automaticely changing from celsius to Fahrenheit. I don't know if it's a normal feature...

**Comment by blackshadev** [comment]
I  had a similar issue with my Aeotec 4 in 1 multisensor. 
What I ended up doing was waking up de device (press a button on the sensor must of the time), and let OpenZwave  assign a return route fort the node, you do this by calling `healNetworkNode` with the second parameter being true. eg `zwave.healNetworkNode(nodeId, true);`. I also healed the whole network beforehand because the network was quite wonky at that point.

But this isn't an issue for this wrapper library since the values (and units) are provided by the device, if they change, the device told the the openZWave library something to let that happen and this repo is just a wrapper around openZWave . So if this persists please post it  on the [OpenZWave github](https://github.com/OpenZWave/open-zwave/issues) along with your log file highlighting the value / unit changes.  (please tag me because I like to know what causes this in more detail as well).

**Comment by ptorrent** [comment]
Hello ! 

Thanks for you answer :).

From my point of view, Zwave is not a reliable protocol (maybe because of wireless ^^). I tested many different participants, each of them have different problems (strangely, problems that are not found on other old protocols ~ 30years ...).

Who can say that it has a Zwave installation that works perfectly?

Anyway thank you for your help, I will try your tip!
