### ISSUE TITLE
Unhandled notification: 28

### ISSUE THREAD

**Issue by jhanssen** [OpenZWave/node-openzwave-shared#27]
I'm getting the following printf on occasion,

```Unhandled notification: 28```

I can also make this happen on demand by calling 
```javascript
zwave.beginControllerCommand("RequestNetworkUpdate")
```

**Comment by ekarak** [comment]
The latest OpenZWave release has merged the beginControllerCommand into the
main notifications stream, that's why you're getting this.

<             Type_ControllerCommand,                /**< When Controller
Commands are executed, Notifications of Success/Failure etc are
communicated via this Notification
<                                                   *
Notification::GetEvent returns Driver::ControllerCommand and
Notification::GetNotification returns Driver::ControllerState */
<             Type_NodeReset                        /**< The Device has
been reset and thus removed from the NodeList in OZW */

I need to work on this, thanks for reporting.


2015-10-08 6:50 GMT+03:00 Jan Erik Hanssen <notifications@github.com>:

> I'm getting the following printf on occasion,
>
> Unhandled notification: 28
>
> I can also make this happen on demand by calling
>
> zwave.beginControllerCommand("RequestNetworkUpdate")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenZWave/node-openzwave-shared/issues/27>.
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by ekarak** [comment]
Please try out [the security branch I've just created.](https://github.com/OpenZWave/node-openzwave-shared/tree/security)
You need to install [my own fork of the OpenZWave library](https://github.com/ekarak/open-zwave) which contains a [vital patch for the pkg-config descriptor](https://github.com/OpenZWave/open-zwave/pull/668)
I've also added some crude documentation for it as well.

**Comment by ekarak** [comment]
The pull request I've committed to the upstream OpenZWave API has been just merged, as such I'm merging this into master. You should simply update (`git pull`) the latest OpenZWave from github, then test my latest code.

Issue resolved.
