### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by cburghardt** [OpenZWave/node-openzwave-shared#342]
Looks like the build of the current version (1.5.6) fails with the current snapshot of openzwave (master):
https://github.com/ioBroker/ioBroker.zwave/issues/79

Related to that: isn't it possible to freeze certain states of openzwave? As soon as they change something in the master the build of your library breaks, that's not the first time.

**Comment by robertsLando** [comment]
Why build based on ozw master? It is not always stable

**Comment by cburghardt** [comment]
Yes and that's the point: as your library doesn't document which version you are compatible with it is difficult to find that out

**Comment by robertsLando** [comment]
The problem is you shouldn’t use openzwave master at all, you should use just releases: https://github.com/OpenZWave/open-zwave/releases. Anyway the library isn’t yet fully compatibile with 1.6 but 1.6 has change lot things with lot of breaking changes that makes it still not “production ready” as you can see there are some bugs. Actually in my project I still use openzwave 1.4 that is the most used and stable atm 

Daniel

**Comment by cburghardt** [comment]
I don't really agree to the statement that 1.6 is not production ready and I wonder how long it will take to adopt ozw-shared when you are also still using 1.4. But anyway, got the message.
