### ISSUE TITLE
Use with the VeraLite

### ISSUE THREAD

**Issue by brock** [OpenZWave/node-openzwave-shared#39]
I notice that all of the instructions default to using a USB zwave device. Is it possible to connect to a zwave device on the network? I'm using a VeraLite on the same network, but not attached via USB.

**Comment by ekarak** [comment]
Sorry, this is not an issue as Vera is not a supported controller (its a completely self-sufficient web miniserver actually)
https://github.com/OpenZWave/open-zwave/wiki/Controller-Compatibility-List
OpenZWave is only meant to work with a locally attached USB or RS232 controllers. 

I _assume_ that Vera has some sort of Web REST API you could use? 

In fact, I was one of the first users of a Vera1 (a rebranded Asus wireless router -- I still have it working on my parent's home!), and it _was_ possible to craft and send HTTP requests to devices, what _wasn't_ possible back then was to define webhooks when a device was controlled manually or via the Vera web interface (so that I had realtime notifications)

**Comment by brock** [comment]
Thanks for that quick reply. That is what I had figured. And yep, the Vera is pretty much like you described, except that I've not found a way to interact with it like an API. Maybe it is there, but I haven't managed to crack it.

Instead I've been using a rubygem over at https://github.com/kreynolds/ruby-mios that does a really great job of sending commands to the Vera. I saw a post on node-red and was intrigued, because I've been doing more node work than ruby stuff lately, and was hoping to be able to hook into the events triggered when I physically switch a device.

Well, thanks for the feedback. I'll just have to plan to "upgrade" my Vera to a USB stick sometime.
