### ISSUE TITLE
AeonLabs Panic Button

### ISSUE THREAD

**Issue by Cloudhomebr** [OpenZWave/node-openzwave-shared#42]
Hi,
What function i use to add a Secondary Controller? Like a http://aeotec.com/z-wave-one-button-remote/766-panic-button-manual-instructions.html

Thanks for any help.

**Comment by ekarak** [comment]
It should be no different than adding a normal device, so you should you use 
- `addNode()` if you're on the latest OpenZWave with the new Security API or 
- `beginControllerCommand('AddDevice') if you have an older OpenZWave version

According to https://groups.google.com/forum/#!topic/openzwave/H74Kpw9Ttjw the button activates a scene, (which binds several devices together: so that eg a light flashes, or a siren starts screaming etc) so you should register a `scene event` handler:
```js
zwave.on('scene event', function (nodeid, sceneid) {
...
```
