### ISSUE TITLE
setValue issue a TypeError

### ISSUE THREAD

**Issue by Vebryn** [OpenZWave/node-openzwave-shared#77]
Hi,

```
console.log('POST setValue nodeid %s classid %s value %s', req.body.nodeid, req.body.classid, req.body.value);
try {
        zwave.setValue({ node_id:req.body.nodeid, class_id:req.body.classid, instance:1, index:0}, req.body.value);
} catch(e) {
        console.log('%s',e);
}
```
This code is working fine but is returning a TypeError.
```
POST setValue nodeid 4 classid 38 value 0
TypeError: wrong value type! 
```
Is it linked with #55 issue ?

Best regards.

**Comment by polarathene** [comment]
Might be silly, but any chance you're passing in strings and not integers? Try `parseInt(req.body.nodeid)`, etc. 

If that isn't it, perhaps add some more details like device and verify it supports class 38 (dimmer?), try some other values, perhaps even just confirm that the commands work with direct values instead of passed in through variables :) ?

**Comment by ekarak** [comment]
This TypeError is emitted because I've recently enforced strict type checking, so that a Boolean ZWave value should be passed in a boolean literal (ie `true` or `false`, but not anything else that can be coerced to a boolean such as a zero-0 or the empty string or nil etc etc)
```
			switch ((*vit).GetType()) {
				case OpenZWave::ValueID::ValueType_Bool: {
					checkType(info[validx]->IsBoolean());
```
Strict type checking apparently creates more problem than it solves in this context and will be removed.

**Comment by ekarak** [comment]
just pushed a minor update to master, can you please do a `git pull` and retry? I removed the strict type checking and you shouldn't be getting any more of these errors.
