### ISSUE TITLE
How to use RemoveNode method to remove a living node?

### ISSUE THREAD

**Issue by jingbosu** [OpenZWave/node-openzwave-shared#95]
I tried to use Manager::RemoveNode(uint32 const _homeId) method to remove a device from my ZWave network, but as this method doesn't take any argument of NodeID, it seems that I can't specify a device to be removed.

To make it clear:
In the method Driver::BeginControllerCommand(ControllerCommand _command, pfnControllerCallback_t _callback, void* _context,	bool _highPower, uint8 _nodeId, uint8 _arg) which RemoveNode called, it takes nodeId as an argument. However RemoveNode put '0' in this parameter when calling BeginControllerCommand() rather than taking a real NodeID.

Maybe I misunderstand something in using OpenZWave library.....Can somebody help me to answer this question?

Thanks in advance for your help,

Sincerely,

Jingbo

**Comment by ekarak** [comment]
Hi, 
You can't remove a node just programmatically, you need to confirm the command by having physical access to the node. So in order to remove a zwave node, you need to 1) invoke the `RemoveNode` command, then 2) *physically go to the node* and start the relevant inclusion/exclusion sequence (eg. press the paddle three times, or use a pencil to push a special inclusion/exclusion button. - this varies by device, so read your device manual)

**Comment by jingbosu** [comment]
Thank you very much for this response so fast! Have a nice day :)
